package GUI;


import javax.swing.*;
import java.awt.*;

public class NewClient extends JFrame {

    public NewClient() {
        setTitle("Nouveau client");
        setSize(450, 200);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        // Layout principal
        JPanel mainPanel = new JPanel(new GridLayout(6, 2));

        // Label "Nom" + Textbox
        JLabel nomLabel = new JLabel("Nom");
        JTextField nomTextBox = new JTextField();
        mainPanel.add(nomLabel);
        mainPanel.add(nomTextBox);

        // Label "Prénom" + Textbox
        JLabel prenomLabel = new JLabel("Prénom");
        JTextField prenomTextBox = new JTextField();
        mainPanel.add(prenomLabel);
        mainPanel.add(prenomTextBox);

        // Label "Date de naissance" + Textbox
        JLabel dateNaissanceLabel = new JLabel("Date de naissance");
        JTextField dateNaissanceTextBox = new JTextField();
        mainPanel.add(dateNaissanceLabel);
        mainPanel.add(dateNaissanceTextBox);

        // Label "Numéro de carte" + Textbox
        JLabel numCarteLabel = new JLabel("Numéro de carte");
        JTextField numCarteTextBox = new JTextField();
        mainPanel.add(numCarteLabel);
        mainPanel.add(numCarteTextBox);

        // Label "email" + Textbox
        JLabel emailLabel = new JLabel("Email");
        JTextField emailTextBox = new JTextField();
        mainPanel.add(emailLabel);
        mainPanel.add(emailTextBox);

        // Boutons
        JPanel buttonsPanel = new JPanel(new FlowLayout());
        JButton enregistrerButton = new JButton("Enregistrer");
        JButton annulerButton = new JButton("Annuler");
        buttonsPanel.add(enregistrerButton);
        buttonsPanel.add(annulerButton);

        // Ajout des composants à la fenêtre
        add(mainPanel, BorderLayout.CENTER);
        add(buttonsPanel, BorderLayout.SOUTH);

        setVisible(true);
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> new NewClient());
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }
}
