package GUI;

import javax.swing.*;
import java.awt.*;

public class NewTravailleur extends JFrame {

    public NewTravailleur() {
        setTitle("Nouveau travailleur");
        setSize(450, 200);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        // Layout principal
        JPanel mainPanel = new JPanel(new GridLayout(6, 2));

        // Label "Nom" + Textbox
        JLabel nomLabel = new JLabel("Nom");
        JTextField nomTextBox = new JTextField();
        nomTextBox.setPreferredSize(new Dimension(nomLabel.getPreferredSize().width, 10)); // Hauteur de 1 cm
        mainPanel.add(nomLabel);
        mainPanel.add(nomTextBox);

        // Label "Prénom" + Textbox
        JLabel prenomLabel = new JLabel("Prénom");
        JTextField prenomTextBox = new JTextField();
        prenomTextBox.setPreferredSize(new Dimension(prenomLabel.getPreferredSize().width, 10)); // Hauteur de 1 cm
        mainPanel.add(prenomLabel);
        mainPanel.add(prenomTextBox);

        // Label "Date de naissance" + Textbox
        JLabel dateNaissanceLabel = new JLabel("Date de naissance");
        JTextField dateNaissanceTextBox = new JTextField();
        dateNaissanceTextBox.setPreferredSize(new Dimension(dateNaissanceLabel.getPreferredSize().width, 10)); // Hauteur de 1 cm
        mainPanel.add(dateNaissanceLabel);
        mainPanel.add(dateNaissanceTextBox);

        // Label "Variable propre" + Textbox
        JLabel variablePropreLabel = new JLabel("Variable propre");
        JTextField variablePropreTextBox = new JTextField();
        variablePropreTextBox.setPreferredSize(new Dimension(variablePropreLabel.getPreferredSize().width, 10)); // Hauteur de 1 cm
        mainPanel.add(variablePropreLabel);
        mainPanel.add(variablePropreTextBox);

        // Liste de choix "Fonction"
        JLabel fonctionLabel = new JLabel("Fonction");
        String[] fonctions = {"Gérant", "Caissier"};
        JComboBox<String> fonctionComboBox = new JComboBox<>(fonctions);
        mainPanel.add(fonctionLabel);
        mainPanel.add(fonctionComboBox);

        // Boutons
        JPanel buttonsPanel = new JPanel(new FlowLayout());
        JButton enregistrerButton = new JButton("Enregistrer");
        JButton annulerButton = new JButton("Annuler");
        buttonsPanel.add(enregistrerButton);
        buttonsPanel.add(annulerButton);

        // Ajout des composants à la fenêtre
        add(mainPanel, BorderLayout.CENTER);
        add(buttonsPanel, BorderLayout.SOUTH);

        setVisible(true);
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> new NewTravailleur());
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }
}
